### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by MrRobotsAA** [xwHoward/WeRollCall#1]
这个直接down下来不可以用吗，我编译不通过啊

**Comment by MrRobotsAA** [comment]
方便的话加下qq好友1094522588

**Comment by xwHoward** [comment]
@axuhongbo 抱歉现在才留意到你的issue，时间已经太久了，估计你已经不需要我的帮助了。这个项目是小程序发布之初写的，很多配置和API相较于当前版本的小程序已经有了很大变动。如果要使用需要进行相应的升级。
